-- Loads all plugin configs.

require "config.colorscheme"
require "config.cmp"
require "config.lsp"
require "config.telescope"
require "config.treesitter"
require "config.autopairs"
require "config.comment"
require "config.gitsigns"
require "config.nvim-tree"
require "config.bufferline"
require "config.lualine"
require "config.project"
require "config.impatient"
require "config.alpha"
require "config.whichkey"
require "config.autocommands"
require "config.hop"
require "config.zen"
require "config.spectre"
require "config.colorizer"
require "config.orgmode"
